### ISSUE TITLE
Question of scope -- other v4l settings?

### ISSUE THREAD

**Issue by mattdm** [soyersoyer/kiyoproctrls#1]
With v4l2ctrl -- or one of the various GUIs that wrap that -- I can set things like Sharpness, Auto/Manual Exposure, Power Line Frequency, and even Zoom (which works by cropping). It'd be kind of convenient to have all of these in one place. Would it be in scope to add these to kiyoproctrls and its GUI?

**Comment by soyersoyer** [comment]
That would be more general, because it could easily support all UVC cameras, and the kiyo pro part should be just an extension. It's a good idea. I will create that project in the weekend.

**Comment by soyersoyer** [comment]
Check out the [cameractrls](https://github.com/soyersoyer/cameractrls). You can set the V4L2, Kiyo Pro, Logitech LED controls in one place.
